# tree not matrix
* only guarantee is at least lane and read per sample

In [32]:
#                          Index four samples with a different number of lanes
SLR = [[[0,1],[0,1]],
       [[0,1],[0,1],[0,1],[0,1]],
       [[0,1]],
       [[0,1],[0,1],[0,1]] ]

for l in SLR:
    print(l)

[[0, 1], [0, 1]]
[[0, 1], [0, 1], [0, 1], [0, 1]]
[[0, 1]]
[[0, 1], [0, 1], [0, 1]]


In [36]:
#                          Find the number of elements in any odd sized list
def get_number_of_elements(some_odd_list):
    n = 0
    
    for l in some_odd_list:
        if isinstance(l, list):
            n += get_number_of_elements(l)
        else:
            n += 1
    return n

n = get_number_of_elements(some_odd_list=SLR)
n

20

In [42]:
#                          get the list of indexes
idx_arr = np.zeros((get_number_of_elements(SLR),3))
count = 0
for r in range(len(SLR)):
    for c in range(len(SLR[r])):
        for rc in range(len(SLR[r][c])):
            idx_arr[count,0] = r
            idx_arr[count,1] = c
            idx_arr[count,2] = rc
            count += 1
idx_arr 

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 2., 0.],
       [1., 2., 1.],
       [1., 3., 0.],
       [1., 3., 1.],
       [2., 0., 0.],
       [2., 0., 1.],
       [3., 0., 0.],
       [3., 0., 1.],
       [3., 1., 0.],
       [3., 1., 1.],
       [3., 2., 0.],
       [3., 2., 1.]])

In [2]:
import numpy as np
#                                define
n_d1 = 2
n_d2 = 3
n_d3 = 2
n = n_d1 * n_d2 * n_d3

#                                allocate
n_d_idx = np.cumsum(np.ones(n))
n_d_arr = n_d_idx.reshape(n_d1, n_d2, n_d3)
print('3 diminsional tensor A:\n',n_d_arr,'\n')

#                                index & iterate
d2_idx = -1
d1_idx = -1
for idx in n_d_idx:
    d3_idx = int(np.mod(idx+n_d3-1, n_d3))
    if d3_idx == 0:
        d2_idx += 1
        d2_idx = int(np.mod(d2_idx, n_d2))
        if d2_idx == 0:
            d1_idx += 1
            d1_idx = int(np.mod(d1_idx, n_d1))
            
    print('%2i\tA[%i,%i,%i] = %3i'%(idx, d1_idx, d2_idx, d3_idx, n_d_arr[d1_idx, d2_idx, d3_idx]))

3 diminsional tensor A:
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]] 

 1	A[0,0,0] =   1
 2	A[0,0,1] =   2
 3	A[0,1,0] =   3
 4	A[0,1,1] =   4
 5	A[0,2,0] =   5
 6	A[0,2,1] =   6
 7	A[1,0,0] =   7
 8	A[1,0,1] =   8
 9	A[1,1,0] =   9
10	A[1,1,1] =  10
11	A[1,2,0] =  11
12	A[1,2,1] =  12
