# Indexing for single normal, multi-tumor, multi-lane, paired ends or not.

In [2]:
import numpy as np
#                                define
n_rows = 3
n_cols = 4
n = n_rows * n_cols

#                                allocate
n_idx = np.cumsum(np.ones(n))
n_arr = n_idx.reshape(n_rows, n_cols)
print('matrix A with %i rows, %i cols, %i elements\n'%(n_rows,n_cols,n))
for r in range(n_rows):
    print(n_arr[r,:])

print('\n\nA[r,c] = n_idx\n')

#                                index & iterate
r = -1
for idx in n_idx:
    c = int(np.mod(idx+n_cols-1,n_cols))
    if c == 0:
        r += 1
        
    print('A[%i,%i] = %3i'%(r, c, n_arr[r,c]))

matrix A with 3 rows, 4 cols, 12 elements

[1. 2. 3. 4.]
[5. 6. 7. 8.]
[ 9. 10. 11. 12.]


A[r,c] = n_idx

A[0,0] =   1
A[0,1] =   2
A[0,2] =   3
A[0,3] =   4
A[1,0] =   5
A[1,1] =   6
A[1,2] =   7
A[1,3] =   8
A[2,0] =   9
A[2,1] =  10
A[2,2] =  11
A[2,3] =  12


In [4]:
import numpy as np
#                                define
n_d1 = 3
n_d2 = 4
n_d3 = 2
n = n_d1 * n_d2 * n_d3

#                                allocate
n_d_idx = np.cumsum(np.ones(n))
n_d_arr = n_d_idx.reshape(n_d1, n_d2, n_d3)
print('3 diminsional tensor A:\n',n_d_arr,'\n')

#                                index & iterate
d2_idx = -1
d1_idx = -1
for idx in n_d_idx:
    d3_idx = int(np.mod(idx+n_d3-1, n_d3))
    if d3_idx == 0:
        d2_idx += 1
        d2_idx = int(np.mod(d2_idx, n_d2))
        if d2_idx == 0:
            d1_idx += 1
            d1_idx = int(np.mod(d1_idx, n_d1))
            
    print('A[%i,%i,%i] = %3i'%(d1_idx, d2_idx, d3_idx, n_d_arr[d1_idx, d2_idx, d3_idx]))

3 diminsional tensor A:
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]
  [13. 14.]
  [15. 16.]]

 [[17. 18.]
  [19. 20.]
  [21. 22.]
  [23. 24.]]] 

A[0,0,0] =   1
A[0,0,1] =   2
A[0,1,0] =   3
A[0,1,1] =   4
A[0,2,0] =   5
A[0,2,1] =   6
A[0,3,0] =   7
A[0,3,1] =   8
A[1,0,0] =   9
A[1,0,1] =  10
A[1,1,0] =  11
A[1,1,1] =  12
A[1,2,0] =  13
A[1,2,1] =  14
A[1,3,0] =  15
A[1,3,1] =  16
A[2,0,0] =  17
A[2,0,1] =  18
A[2,1,0] =  19
A[2,1,1] =  20
A[2,2,0] =  21
A[2,2,1] =  22
A[2,3,0] =  23
A[2,3,1] =  24
