In [1]:
import numpy as np
#                                define
n_d1 = 4
n_d2 = 3
n_d3 = 2
n = n_d1 * n_d2 * n_d3

#                                allocate
n_d_idx = np.cumsum(np.ones(n))
n_d_arr = n_d_idx.reshape(n_d1, n_d2, n_d3)
print('3 diminsional tensor A:\n',n_d_arr,'\n')

#                                index & iterate
d2_idx = -1
d1_idx = -1
for idx in n_d_idx:
    d3_idx = int(np.mod(idx+n_d3-1, n_d3))
    if d3_idx == 0:
        d2_idx += 1
        d2_idx = int(np.mod(d2_idx, n_d2))
        if d2_idx == 0:
            d1_idx += 1
            d1_idx = int(np.mod(d1_idx, n_d1))
            
    print('%2i\tA[%i,%i,%i] = %3i'%(idx, d1_idx, d2_idx, d3_idx, n_d_arr[d1_idx, d2_idx, d3_idx]))

3 diminsional tensor A:
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]

 [[13. 14.]
  [15. 16.]
  [17. 18.]]

 [[19. 20.]
  [21. 22.]
  [23. 24.]]] 

 1	A[0,0,0] =   1
 2	A[0,0,1] =   2
 3	A[0,1,0] =   3
 4	A[0,1,1] =   4
 5	A[0,2,0] =   5
 6	A[0,2,1] =   6
 7	A[1,0,0] =   7
 8	A[1,0,1] =   8
 9	A[1,1,0] =   9
10	A[1,1,1] =  10
11	A[1,2,0] =  11
12	A[1,2,1] =  12
13	A[2,0,0] =  13
14	A[2,0,1] =  14
15	A[2,1,0] =  15
16	A[2,1,1] =  16
17	A[2,2,0] =  17
18	A[2,2,1] =  18
19	A[3,0,0] =  19
20	A[3,0,1] =  20
21	A[3,1,0] =  21
22	A[3,1,1] =  22
23	A[3,2,0] =  23
24	A[3,2,1] =  24


In [10]:
def get_tensor_idx(idx, dims_array):
    
    if idx > np.prod(dims_array):
        print('INPUT FAIL')
        
    print(idx, dims_array, np.prod(dims_array), dims_array.shape)

idx = 5
dims_array = np.array([2,2,2])
get_tensor_idx(idx, dims_array)

5 [2 2 2] 8 (3,)
