# Indexing for single normal, multi-tumor, multi-lane, paired ends or not.

In [ ]:
import numpy as np
#                                define
n_rows = 3
n_cols = 4
n = n_rows * n_cols

#                                allocate
n_idx = np.cumsum(np.ones(n))
n_arr = n_idx.reshape(n_rows, n_cols)
print('matrix A with %i rows, %i cols, %i elements\n'%(n_rows,n_cols,n))
for r in range(n_rows):
    print(n_arr[r,:])

print('\n\nA[r,c] = n_idx\n')

#                                index & iterate
r = -1
for idx in n_idx:
    c = int(np.mod(idx+n_cols-1,n_cols))
    if c == 0:
        r += 1
        
    print('A[%i,%i] = %3i'%(r, c, n_arr[r,c]))

In [ ]:
import numpy as np
#                                define
n_d1 = 3
n_d2 = 4
n_d3 = 2
n = n_d1 * n_d2 * n_d3

#                                allocate
n_d_idx = np.cumsum(np.ones(n))
n_d_arr = n_d_idx.reshape(n_d1, n_d2, n_d3)
print('3 diminsional tensor A:\n',n_d_arr,'\n')

#                                index & iterate
d2_idx = -1
d1_idx = -1
for idx in n_d_idx:
    d3_idx = int(np.mod(idx+n_d3-1, n_d3))
    if d3_idx == 0:
        d2_idx += 1
        d2_idx = int(np.mod(d2_idx, n_d2))
        if d2_idx == 0:
            d1_idx += 1
            d1_idx = int(np.mod(d1_idx, n_d1))
            
    print('A[%i,%i,%i] = %3i'%(d1_idx, d2_idx, d3_idx, n_d_arr[d1_idx, d2_idx, d3_idx]))

## multi-sample, multi-lane, single or multi read
* (change reads to 1 for demo)

In [12]:
import numpy as np
#                                define test data
samples = 4
lanes = 3
reads = 2
n = samples * lanes * reads

#                                allocate test data
n_d_idx = np.cumsum(np.ones(n))
multi_sample_arr = n_d_idx.reshape(samples, lanes, reads)
print('%i x %i x %i tensor A:\n'%(samples, lanes, reads), 
      multi_sample_arr,'\n')

#                                algorithm: index & iterate
lanes_idx = -1
samples_idx = -1
for idx in n_d_idx:
    reads_idx = int(np.mod(idx + reads-1, reads))
    if reads_idx == 0:
        lanes_idx += 1
        lanes_idx = int(np.mod(lanes_idx, lanes))
        if lanes_idx == 0:
            samples_idx += 1
            samples_idx = int(np.mod(samples_idx, samples))
            
    print('linear index:%3i = A[%i,%i,%i] = %3i'%(idx, 
                                                  samples_idx, 
                                                  lanes_idx, 
                                                  reads_idx, 
                                                  multi_sample_arr[samples_idx, 
                                                                   lanes_idx, 
                                                                   reads_idx] ) )

4 x 3 x 2 tensor A:
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]

 [[13. 14.]
  [15. 16.]
  [17. 18.]]

 [[19. 20.]
  [21. 22.]
  [23. 24.]]] 

linear index:  1 = A[0,0,0] =   1
linear index:  2 = A[0,0,1] =   2
linear index:  3 = A[0,1,0] =   3
linear index:  4 = A[0,1,1] =   4
linear index:  5 = A[0,2,0] =   5
linear index:  6 = A[0,2,1] =   6
linear index:  7 = A[1,0,0] =   7
linear index:  8 = A[1,0,1] =   8
linear index:  9 = A[1,1,0] =   9
linear index: 10 = A[1,1,1] =  10
linear index: 11 = A[1,2,0] =  11
linear index: 12 = A[1,2,1] =  12
linear index: 13 = A[2,0,0] =  13
linear index: 14 = A[2,0,1] =  14
linear index: 15 = A[2,1,0] =  15
linear index: 16 = A[2,1,1] =  16
linear index: 17 = A[2,2,0] =  17
linear index: 18 = A[2,2,1] =  18
linear index: 19 = A[3,0,0] =  19
linear index: 20 = A[3,0,1] =  20
linear index: 21 = A[3,1,0] =  21
linear index: 22 = A[3,1,1] =  22
linear index: 23 = A[3,2,0] =  23
linear index: 24 = A[3,2,1] =  24


# Multi-Normal with Multi-Sample, multi-lane, single or multi read
## Each must have one or more members.

In [4]:
import numpy as np
#                                define test data
normals = 2
samples = 4
lanes = 3
reads = 2
n = normals * samples * lanes * reads

#                                allocate test data
n_d_idx = np.cumsum(np.ones(n))
multi_sample_arr = n_d_idx.reshape(normals, samples, lanes, reads)
print('%i x %i x %i x %i tensor A:\n'%(normals, samples, lanes, reads), 
      multi_sample_arr,'\n')

#                                algorithm: index & iterate
lanes_idx = -1
samples_idx = -1
normals_idx = -1
for idx in n_d_idx:
    reads_idx = int(np.mod(idx - 1, reads))
    if reads_idx == 0:
        lanes_idx += 1
        lanes_idx = int(np.mod(lanes_idx, lanes))
        if lanes_idx == 0:
            samples_idx += 1
            samples_idx = int(np.mod(samples_idx, samples))
            if samples_idx == 0:
                normals_idx += 1
                normals_idx = int(np.mod(normals_idx, normals))
            
    print('linear index:%3i = A[%i,%i,%i,%i] = %3i'%(idx, 
                                                  normals_idx,
                                                  samples_idx, 
                                                  lanes_idx, 
                                                  reads_idx, 
                                                  multi_sample_arr[normals_idx, 
                                                                   samples_idx, 
                                                                   lanes_idx, 
                                                                   reads_idx] ) )

2 x 4 x 3 x 2 tensor A:
 [[[[ 1.  2.]
   [ 3.  4.]
   [ 5.  6.]]

  [[ 7.  8.]
   [ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]
   [17. 18.]]

  [[19. 20.]
   [21. 22.]
   [23. 24.]]]


 [[[25. 26.]
   [27. 28.]
   [29. 30.]]

  [[31. 32.]
   [33. 34.]
   [35. 36.]]

  [[37. 38.]
   [39. 40.]
   [41. 42.]]

  [[43. 44.]
   [45. 46.]
   [47. 48.]]]] 

linear index:  1 = A[0,0,0,0] =   1
linear index:  2 = A[0,0,0,1] =   2
linear index:  3 = A[0,0,1,0] =   3
linear index:  4 = A[0,0,1,1] =   4
linear index:  5 = A[0,0,2,0] =   5
linear index:  6 = A[0,0,2,1] =   6
linear index:  7 = A[0,1,0,0] =   7
linear index:  8 = A[0,1,0,1] =   8
linear index:  9 = A[0,1,1,0] =   9
linear index: 10 = A[0,1,1,1] =  10
linear index: 11 = A[0,1,2,0] =  11
linear index: 12 = A[0,1,2,1] =  12
linear index: 13 = A[0,2,0,0] =  13
linear index: 14 = A[0,2,0,1] =  14
linear index: 15 = A[0,2,1,0] =  15
linear index: 16 = A[0,2,1,1] =  16
linear index: 17 = A[0,2,2,0] =  17
linear index: 18 = A[0,2,2,1] 

In [17]:
a = np.cumsum(np.ones(13))
np.int_(np.floor((a-1) / 3))

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4])